### PR TITLE
Design/header

### PR DESCRIPTION
**Pull request by emgerold**
- added header with logo and profile link

### CODE REVIEW

**Comment by mischakolbe** [comment]
Since this seems to be a branch that mixes some changes of the overall HTML cleanup branch and the header, I will only look at the resulting page, not (yet) at the code. Hopefully that will become a lot clearer to review, once the other branch is merged.

Since the profile button at the top will exist, I wonder whether we shouldn't just remove the one from the bottom already. Even if we'd only have 3 buttons temporarily... I wouldn't mind. What do you think, @emgerold  & @conradbielitz ?

Plus; screen real estate is going to be very, very precious when we add features like the map. Should we try and shave off a few pixels at the top & bottom bar? Maybe just 5-10px would help a bit later on:
image


Apart from this; looking slick!!

**Comment by conradbielitz** [comment]
I agree Mischa, as we have the profile icon in the header, we can delete it in the navbar and merge it already from my POV!

**Comment by emgerold** [comment]
Yeah, sorry for the mix up here. 

Let’s add the new header when the map is ready.

**Comment by mischakolbe** [comment]
Closing PR in favor of https://github.com/portato-io/portatoapp/pull/279

**Pull request closed without merging**
