### PR TITLE
refactors function and fixes issue

### PR DESCRIPTION
**Pull request by hugo2410**
<h2>Changes proposed in this pull request:</h2>

Fixes email sending to the users when they submit their send requests

<h2>Performed test by PR author:</h2>

tested in dev environment

### CODE REVIEW

**Comment by hugo2410** [comment]
@conradbielitz can you have a look at the email and feel free to modify or let me know what i should add/change

**Comment by conradbielitz** [comment]
Thanks @hugo2410!

A few comments on this, see also image attached
1) German version should read: "Bestätigung deines Transportauftrages"
2) Can the sender simply be "Portato" ?
3.1) Would be great if we can expand the text a bit: e.g. 
***
Dear [displayName], 

thank you very much for your shipment request. Please find a summary of it below. 
We will reach out to you soon with a suggestion for a driver who is going your way. You can manage your request at any time under this link: [link].

Best regards,
your Portato Team
***
3.2. German version
*** 
Liebe/r [displayName],

vielen Dank für deinen Transportauftrag. Wir melden uns bei Dir sobald wie möglich mit Fahrer:innen, die in deine Richtung fahren und den Transport übernehmen können. 

Deinen Auftrag kannst du unter diesem Link jederzeit aufrufen, editieren oder löschen: [link].

Vielen Dank, 
dein Portato Team

4. Can we left align this?
5. There's some issue with the translation file variable

image

**Comment by hugo2410** [comment]
@conradbielitz I've updated it, taken into account all your comments can you please check if they are any remaining issues

**Comment by conradbielitz** [comment]
Hey @hugo2410, I did some minor tweaks to the email, mostly optics, and moved the translation file into the requestSummary block. I think we can HTML-style the email even better, maybe with the help of Moritz, when we have some time for it. But for now all good from my end on this PR.

**Review by conradbielitz — APPROVED** [review]
good to go

**Pull request merged**
